structurizr-onpremises/src/main/java/com/structurizr/onpremises/domain/Image.java
package com.structurizr.onpremises.domain;

import java.util.Date;

public class Image {

    private final String name;
    private final long size;
    private final Date lastModifiedDate;
    private String url;

    public Image(String name, long size, Date lastModifiedDate) {
        this.name = name;
        this.size = size;
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getName() {
        return name;
    }

    public long getSizeInKB() {
        return size / 1024;
    }

    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}

structurizr-onpremises/src/main/java/com/structurizr/onpremises/web/home/HomePageController.java
package com.structurizr.onpremises.web.home;

import com.structurizr.onpremises.component.workspace.WorkspaceMetaData;
import com.structurizr.onpremises.util.Configuration;
import com.structurizr.onpremises.util.Features;
import com.structurizr.onpremises.util.HtmlUtils;
import com.structurizr.onpremises.web.AbstractController;
import com.structurizr.util.StringUtils;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.*;

@Controller
public class HomePageController extends AbstractController {

    private static final String SORT_DATE = "date";
    private static final String SORT_NAME = "name";

    private static final String DEFAULT_PAGE_NUMBER = "1";
    private static final String DEFAULT_PAGE_SIZE = "" + PaginatedWorkspaceList.DEFAULT_PAGE_SIZE;

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String showUnauthenticatedHomePage(
            @RequestParam(required = false, defaultValue = SORT_NAME) String sort,
            @RequestParam(required = false, defaultValue = DEFAULT_PAGE_NUMBER) int pageNumber,
            @RequestParam(required = false, defaultValue = DEFAULT_PAGE_SIZE) int pageSize,
            ModelMap model) {

        if (isAuthenticated()) {
            return "redirect:/dashboard";
        }

        sort = determineSort(sort);
        List<WorkspaceMetaData> workspaces = sortAndPaginate(new ArrayList<>(workspaceComponent.getWorkspaces(null)), sort, pageNumber, pageSize, model);

        model.addAttribute("workspaces", workspaces);
        model.addAttribute("numberOfWorkspaces", workspaces.size());
        model.addAttribute("sort", sort);

        addCommonAttributes(model, "", true);

        return "home";
    }

    @RequestMapping(value = "/dashboard", method = RequestMethod.GET)
    @PreAuthorize("isAuthenticated()")
    public String showAuthenticatedDashboard(
            @RequestParam(required = false, defaultValue = SORT_NAME) String sort,
            @RequestParam(required = false, defaultValue = DEFAULT_PAGE_NUMBER) int pageNumber,
            @RequestParam(required = false, defaultValue = DEFAULT_PAGE_SIZE) int pageSize,
            ModelMap model) {

        sort = determineSort(sort);
        List<WorkspaceMetaData> workspaces = sortAndPaginate(new ArrayList<>(workspaceComponent.getWorkspaces(getUser())), sort, pageNumber, pageSize, model);

        model.addAttribute("workspaces", workspaces);
        model.addAttribute("numberOfWorkspaces", workspaces.size());
        model.addAttribute("sort", sort);

        model.addAttribute("userCanCreateWorkspace", Configuration.getInstance().getAdminUsersAndRoles().isEmpty() || getUser().isAdmin());
        model.addAttribute("userCanCreateDiagramReview", Configuration.getInstance().isFeatureEnabled(Features.DIAGRAM_REVIEWS));

        addCommonAttributes(model, "", true);

        return "dashboard";
    }

    private List<WorkspaceMetaData> sortAndPaginate(List<WorkspaceMetaData> workspaces, String sort, int pageNumber, int pageSize, ModelMap model) {
        if (SORT_DATE.equals(sort)) {
            workspaces.sort((wmd1, wmd2) -> wmd2.getLastModifiedDate().compareTo(wmd1.getLastModifiedDate()));
        } else {
            workspaces.sort(Comparator.comparing(wmd -> wmd.getName().toLowerCase()));
        }

        if (workspaces.isEmpty() || pageSize >= workspaces.size()) {
            return workspaces;
        } else {
            PaginatedWorkspaceList paginatedWorkspaceList = new PaginatedWorkspaceList(workspaces, pageNumber, pageSize);

            model.addAttribute("pageNumber", paginatedWorkspaceList.getPageNumber());
            if (paginatedWorkspaceList.hasPreviousPage()) {
                model.addAttribute("previousPage", pageNumber - 1);
            }
            if (paginatedWorkspaceList.hasNextPage()) {
                model.addAttribute("nextPage", pageNumber + 1);
            }

            model.addAttribute("maxPage", paginatedWorkspaceList.getMaxPage());

            model.addAttribute("pageSize", paginatedWorkspaceList.getPageSize());

            return paginatedWorkspaceList.getWorkspaces();
        }
    }

    private String determineSort(String sort) {
        sort = HtmlUtils.filterHtml(sort);

        if (!StringUtils.isNullOrEmpty(sort) && sort.trim().equals(SORT_DATE)) {
            sort = SORT_DATE;
        } else {
            sort = SORT_NAME;
        }

        return sort;
    }

}

structurizr-onpremises/src/main/java/com/structurizr/onpremises/web/security/SignInController.java
package com.structurizr.onpremises.web.security;

import com.structurizr.onpremises.web.AbstractController;
import jakarta.servlet.Filter;
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.security.web.FilterChainProxy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class SignInController extends AbstractController implements ApplicationContextAware {

    private static final String STRUCTURIZR_USERNAME_COOKIE_NAME = "structurizr.username";
    private static final String FILTER_CHAIN_PROXY_BEAN_NAME = "org.springframework.security.filterChainProxy";

    private ApplicationContext applicationContext;

    @RequestMapping(value = "/signin", method = RequestMethod.GET)
    public String getSignInPage(@CookieValue(value=STRUCTURIZR_USERNAME_COOKIE_NAME,defaultValue="") String username, ModelMap model) {
        if (username != null && username.length() > 0) {
            model.addAttribute("username", username);
        }

        // only show the "remember me" checkbox if the RememberMeAuthenticationFilter is configured
        boolean rememberMeEnabled = false;
        FilterChainProxy filterChainProxy = (FilterChainProxy)applicationContext.getBean(FILTER_CHAIN_PROXY_BEAN_NAME);
        if (filterChainProxy != null) {
            for (SecurityFilterChain filterChain : filterChainProxy.getFilterChains()) {
                for (Filter filter : filterChain.getFilters()) {
                    if (filter instanceof RememberMeAuthenticationFilter) {
                        rememberMeEnabled = true;
                    }
                }
            }
        }

        model.addAttribute("rememberMeEnabled", rememberMeEnabled);
        addCommonAttributes(model, "Sign in", true);

        return "signin";
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }

}

structurizr-onpremises/src/main/java/com/structurizr/onpremises/web/user/UserProfileController.java
package com.structurizr.onpremises.web.user;

import com.structurizr.onpremises.web.AbstractController;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class UserProfileController extends AbstractController {

    private static final String VIEW = "user-profile";

    @RequestMapping(value = "/user/profile", method = RequestMethod.GET)
    @PreAuthorize("isAuthenticated()")
    public String showUserProfilePage(ModelMap model) {
        model.addAttribute("user", getUser());

        addCommonAttributes(model, "User Profile", true);

        return VIEW;
    }

}

structurizr-onpremises/src/main/java/com/structurizr/onpremises/web/workspace/DslEditorController.java
package com.structurizr.onpremises.web.workspace;

import com.structurizr.Workspace;
import com.structurizr.dsl.DslUtils;
import com.structurizr.dsl.StructurizrDslParser;
import com.structurizr.dsl.StructurizrDslParserException;
import com.structurizr.onpremises.component.workspace.WorkspaceMetaData;
import com.structurizr.onpremises.domain.User;
import com.structurizr.onpremises.util.Configuration;
import com.structurizr.onpremises.util.HtmlUtils;
import com.structurizr.onpremises.util.WorkspaceValidationUtils;
import com.structurizr.util.StringUtils;
import com.structurizr.util.WorkspaceUtils;
import com.structurizr.validation.WorkspaceScopeValidationException;
import com.structurizr.validation.WorkspaceScopeValidatorFactory;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

@Controller
@PreAuthorize("isAuthenticated()")
public class DslEditorController extends AbstractWorkspaceEditorController {

    private static final Log log = LogFactory.getLog(DslEditorController.class);

    protected static final String VIEW = "dsl-editor";

    @RequestMapping(value = "/workspace/{workspaceId}/dsl", method = RequestMethod.GET)
    public String showAuthenticatedDslEditor(
            @PathVariable("workspaceId") long workspaceId,
            @RequestParam(required = false) String version,
            ModelMap model
    ) {
        if (!Configuration.getInstance().isDslEditorEnabled()) {
            return showError("dsl-editor-disabled", model);
        }

        WorkspaceMetaData workspaceMetaData = workspaceComponent.getWorkspaceMetaData(workspaceId);
        if (workspaceMetaData == null) {
            return show404Page(model);
        }

        if (workspaceMetaData.isClientEncrypted()) {
            return showError("workspace-is-client-side-encrypted", model);
        }

        model.addAttribute("publishThumbnails", true);
        model.addAttribute("quickNavigationPath", "diagram-editor");
        try {
            model.addAttribute("dslVersion", Class.forName(StructurizrDslParser.class.getCanonicalName()).getPackage().getImplementationVersion());
        } catch (ClassNotFoundException e) {
            // ignore
        }

        if (!workspaceMetaData.hasNoUsersConfigured() && !workspaceMetaData.isWriteUser(getUser())) {
            if (workspaceMetaData.isReadUser(getUser())) {
                return showError("workspace-is-readonly", model);
            } else {
                return show404Page(model);
            }
        }

        return lockWorkspaceAndShowAuthenticatedView(VIEW, workspaceMetaData, version, model, false);
    }

    @RequestMapping(value = "/workspace/{workspaceId}/dsl", method = RequestMethod.POST, produces = "application/json; charset=UTF-8")
    @ResponseBody
    public DslEditorResponse postToDslEditor(
            @PathVariable("workspaceId") long workspaceId,
            @RequestBody String json
    ) {
        WorkspaceMetaData workspaceMetaData = workspaceComponent.getWorkspaceMetaData(workspaceId);
        if (workspaceMetaData == null) {
            return new DslEditorResponse(false, "404");
        }

        User user = getUser();
        if (!workspaceMetaData.hasNoUsersConfigured() && !workspaceMetaData.isWriteUser(getUser())) {
            return new DslEditorResponse(false, "404");
        }

        try {
            Workspace oldWorkspace = WorkspaceUtils.fromJson(json);

            String dsl = DslUtils.getDsl(oldWorkspace);
            if (StringUtils.isNullOrEmpty(dsl)) {
                dsl = String.format(DSL_TEMPLATE, workspaceMetaData.getName(), workspaceMetaData.getDescription());
            }

            try {
                Workspace newWorkspace = fromDsl(dsl);
                newWorkspace.setId(workspaceId);
                newWorkspace.setLastModifiedDate(new Date());
                newWorkspace.getViews().copyLayoutInformationFrom(oldWorkspace.getViews());

                newWorkspace.getViews().getConfiguration().copyConfigurationFrom(oldWorkspace.getViews().getConfiguration());

                return new DslEditorResponse(WorkspaceUtils.toJson(newWorkspace, false));
            } catch (StructurizrDslParserException | WorkspaceScopeValidationException e) {
                String errorMessage = e.getMessage();

                return new DslEditorResponse(false, errorMessage);
            }
        } catch (Exception e) {
            if (!(e instanceof StructurizrDslParserException)) {
                log.error("Error converting DSL to JSON", e);
            }

            return new DslEditorResponse(false, e.getMessage());
        }
    }

    private Workspace fromDsl(String dsl) throws StructurizrDslParserException, WorkspaceScopeValidationException {
        StructurizrDslParser parser = new StructurizrDslParser();
        parser.setRestricted(true);
        parser.parse(dsl);

        Workspace workspace = parser.getWorkspace();
        DslUtils.setDsl(workspace, dsl);

        // add default views if no views are explicitly defined
        if (!workspace.getModel().isEmpty() && workspace.getViews().isEmpty()) {
            workspace.getViews().createDefaultViews();
        }

        WorkspaceValidationUtils.validateWorkspaceScope(workspace);

        return workspace;
    }

    private static final String DSL_TEMPLATE = """
            workspace "%s" "%s" {

                model {
                }

                views {
                }
               \s
            }""";

}

structurizr-onpremises/src/main/java/com/structurizr/onpremises/web/workspace/ImagesController.java
package com.structurizr.onpremises.web.workspace;

import com.structurizr.onpremises.component.workspace.WorkspaceMetaData;
import com.structurizr.onpremises.domain.Image;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

@Controller
public class ImagesController extends AbstractWorkspaceController {

    private static final String VIEW = "images";

    @RequestMapping(value = "/workspace/{workspaceId}/images", method = RequestMethod.GET)
    @PreAuthorize("isAuthenticated()")
    public String showAuthenticatedImages(
            @PathVariable("workspaceId") long workspaceId,
            ModelMap model
    ) {
        WorkspaceMetaData workspaceMetaData = workspaceComponent.getWorkspaceMetaData(workspaceId);
        if (workspaceMetaData == null) {
            return show404Page(model);
        }

        if (userCanAccessWorkspace(workspaceMetaData)) {
            List<Image> images = workspaceComponent.getImages(workspaceId);
            for (Image image : images) {
                if (workspaceMetaData.isOpen()) {
                    image.setUrl("/share/" + workspaceId + "/images/" + image.getName());
                } else if (workspaceMetaData.isShareable()) {
                    image.setUrl("/share/" + workspaceId + "/" + workspaceMetaData.getSharingToken() + "/images/" + image.getName());
                }
            }

            images = images.stream().filter(i -> !i.getName().endsWith("thumbnail.png")).collect(Collectors.toList());
            images.sort(Comparator.comparing(i -> i.getName().toLowerCase()));

            model.addAttribute("images", images);

            boolean editable = workspaceMetaData.hasNoUsersConfigured() || workspaceMetaData.isWriteUser(getUser());

            return showAuthenticatedView(VIEW, workspaceMetaData, null, model, true, editable);
        }

        return show404Page(model);
    }

    @RequestMapping(value = "/workspace/{workspaceId}/images/delete", method = RequestMethod.POST)
    public String deletePublishedImages(@PathVariable("workspaceId") long workspaceId, ModelMap model) {
        WorkspaceMetaData workspaceMetaData = workspaceComponent.getWorkspaceMetaData(workspaceId);
        if (workspaceMetaData == null) {
            return show404Page(model);
        }
        if (workspaceMetaData.hasNoUsersConfigured() || workspaceMetaData.isWriteUser(getUser())) {
            workspaceComponent.deleteImages(workspaceId);
        }

        return "redirect:/workspace/" + workspaceId + "/images";
    }

}

structurizr-onpremises/src/main/webapp/WEB-INF/views/dashboard.jsp
<%@ include file="/WEB-INF/fragments/quick-navigation.jspf" %>

<div id="dashboard" class="section" style="padding-bottom: 0px">
    <div>
        <%@ include file="/WEB-INF/fragments/dashboard-workspaces.jspf" %>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/feature-not-available.jsp
<div class="section">
    <div class="container">
        <h1>Feature not available</h1>
        <p>
            This feature is not avaiable on this installation.
        </p>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/home.jsp
<%@ include file="/WEB-INF/fragments/quick-navigation.jspf" %>

<div id="dashboard" class="section" style="padding-bottom: 0px">
    <div>
        <%@ include file="/WEB-INF/fragments/dashboard-workspaces.jspf" %>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/images.jsp
<div class="section">
    <div class="container centered">
        <h1>Images</h1>
        <p>
            Structurizr supports the ability to embed diagrams via a static PNG file via a regular image tag in HTML, Markdown, AsciiDoc, etc.
            <br />
            See <a href="https://structurizr.com/help/embed-image" target="_blank">Image embed</a> for more details.
        </p>
        <p class="smaller">
            (<a href="/workspace/${workspaceId}">back to workspace summary</a>)
        </p>

        <br />

        <c:choose>
        <c:when test="${not empty images}">
        <div class="centered">
        <c:forEach var="image" items="${images}">
            <div style="display: inline-block; margin: 10px 10px 40px 10px; max-width: 200px;">
                <a href="${image.url}" target="_blank"><img src="${image.url}" class="thumbnail viewThumbnail" width="200px" /></a>
                <p class="smaller">
                    <b>${image.name}</b>
                    <br />
                    <fmt:formatDate value="${image.lastModifiedDate}" pattern="EEE dd MMM yyyy HH:mm z" timeZone="${user.timeZone}" />
                    <br />
                    ${image.sizeInKB} KB
                </p>
            </div>
        </c:forEach>
        </div>

        <c:if test="${workspace.editable}">
        <div class="centered">
            <form id="deleteImagesForm" class="form-inline small centered" style="display: inline-block; margin-bottom: 5px" action="/workspace/${workspace.id}/images/delete" method="post">
                <button class="btn btn-default" type="submit" name="action" value="delete" title="Delete published images"><img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/trash3.svg" class="icon-btn" /> Delete published images</button>
            </form>
        </div>
        </c:if>

        </c:when>
            <c:otherwise>
        <p class="centered smaller" style="margin-top: 40px">
            No images have been published for this workspace.
        </p>
            </c:otherwise>
        </c:choose>
    </div>
</div>

<script nonce="${scriptNonce}">
    $('.viewThumbnail').on('error', function() {
        $(this).on('error', undefined);
        $(this).attr('src', '/static/img/thumbnail-not-available.png');
    });

    $('#deleteImagesForm').on('submit', function() {
        return confirm('Are you sure you want to delete the published images?');
    });
</script>

structurizr-onpremises/src/main/webapp/WEB-INF/views/search-results.jsp
<div class="section">
    <div class="container">
        <h1><c:out value="${query}" /></h1>

        <div class="centered">
            <form id="searchForm" method="get" action="/search" style="display: inline-block">
                <div class="form-inline" style="margin-top: 8px">
                    <div class="form-group">
                        <div class="btn-group">
                            <input type="text" name="query" class="form-control" placeholder="Search" value="${query}" style="width: 400px" />
                            <c:if test="${not empty workspaceId}">
                                <input type="hidden" name="workspaceId" class="form-control" value="${workspaceId}" />
                            </c:if>
                            <select class="form-control" name="category">
                                <option value="">All</option>
                                <c:if test="${empty workspaceId}">
                                    <option value="workspace" <c:if test="${category eq 'workspace'}">selected="selected"</c:if>>Workspaces</option>
                                </c:if>
                                <option value="diagram" <c:if test="${category eq 'diagram'}">selected="selected"</c:if>>Diagrams</option>
                                <option value="documentation" <c:if test="${category eq 'documentation'}">selected="selected"</c:if>>Documentation</option>
                                <option value="decision" <c:if test="${category eq 'decision'}">selected="selected"</c:if>>Decisions</option>
                            </select>
                        </div>
                        <div class="btn-group">
                            <button id="searchButton" class="btn btn-default" title="Search" style="height: 33px;"><img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/search.svg" class="icon-btn" /></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <br />

        <c:choose>
            <c:when test="${not empty results}">
                <table class="table table-striped small">

                    <c:forEach var="result" items="${results}">
                        <tr>
                            <td width="90px">
                                <div>
                                    <img src="${result.workspace.urlPrefix}/${result.workspaceId}/images/thumbnail.png" width="70px" alt="<c:out value='${result.workspace.name}' escapeXml='true' />" class="thumbnail workspaceThumbnail" />
                                </div>
                            </td>
                            <td>
                                <c:choose>
                                    <c:when test="${result.type eq 'workspace'}">
                                        <img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/folder.svg" class="icon-sm" />
                                    </c:when>
                                    <c:when test="${result.type eq 'documentation'}">
                                        <img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/book.svg" class="icon-sm" />
                                    </c:when>
                                    <c:when test="${result.type eq 'decision'}">
                                        <img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/journal-text.svg" class="icon-sm" />
                                    </c:when>
                                    <c:when test="${result.type eq 'diagram'}">
                                        <img src="${structurizrConfiguration.cdnUrl}/bootstrap-icons/bounding-box.svg" class="icon-sm" />
                                    </c:when>
                                </c:choose>
                                <a href="${result.workspace.urlPrefix}/${result.workspaceId}${result.url}"><c:out value="${result.name}" escapeXml="true" /></a>
                                <c:if test="${result.type ne 'workspace'}">
                                <div class="smaller">
                                    (from <a href="${result.workspace.urlPrefix}/${result.workspace.id}"><c:out value="${result.workspace.name}" escapeXml="true" /></a>)
                                </div>
                                </c:if>
                                <div class="smaller" style="margin-top: 5px">
                                    <c:out value="${result.description}" escapeXml="true" />
                                </div>
                            </td>
                        </tr>
                    </c:forEach>

                </table>
            </c:when>
            <c:otherwise>
                <p>
                    No results found.
                </p>
            </c:otherwise>
        </c:choose>
    </div>
</div>

<script nonce="${scriptNonce}">
    $('.workspaceThumbnail').on('error', function() {
        $(this).on('error', undefined);
        $(this).attr('src', '/static/img/thumbnail-not-available.png');
    });

    $('#searchButton').click(function() { $('#searchForm').submit(); });
</script>

structurizr-onpremises/src/main/webapp/WEB-INF/views/signin.jsp
<c:set var="usernameRemembered" value="${not empty username}" />

<div class="section">
    <div class="container">

        <c:if test="${not empty param['error']}">
            <div class="alert alert-danger small" role="alert">Sorry, that username/password combination wasn't recognised - please try again.</div>
        </c:if>

        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 centered">
                <form class="form-horizontal" action="/login" method="post" role="form">
                    <h1 class="centered">Sign in</h1>
                    <br />

                    <input type="text" class="form-control" id="username" name="username" value="${username}" placeholder="Username" required="true" autocomplete="on" <c:if test="${not usernameRemembered}">autofocus="true"</c:if> />
                    <input id="password" class="form-control" style="margin-top: 10px;" id="password" name="password" placeholder="Password" type="password" required="true" autocomplete="off" <c:if test="${usernameRemembered}">autofocus="true"</c:if> />

                    <div class="centered" style="margin-top: 10px;">
                        <span id="showPassword" class="label structurizrBackgroundLighter" style="cursor:default;"><img src="/static/bootstrap-icons/eye.svg" class="icon-sm icon-white" /> Show password</span>
                        <span id="hidePassword" class="label structurizrBackgroundLighter hidden" style="cursor:default;"><img src="/static/bootstrap-icons/eye-slash.svg" class="icon-sm icon-white" /> Hide password</span>
                    </div>

                    <div class="centered" style="margin-top: 10px;">
                        <c:if test="${pageContext.request.secure}">
                        <input type="checkbox" id="rememberUsername" name="rememberUsername" value="true" <c:if test="${usernameRemembered}">checked="checked"</c:if> />
                        <label for="rememberUsername" class="small">Remember e-mail address</label>
                        <br />
                        <input type="checkbox" id="rememberMe" name="remember-me" value="true" />
                        <label for="rememberMe" class="small">Stay signed in</label>
                        </c:if>

                        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
                        <input type="hidden" id="hash" name="hash" value="" />
                    </div>

                    <div class="centered" style="margin-top: 30px;">
                        <button id="submit" type="submit" class="btn btn-default">Sign In</button>
                    </div>
                </form>
                <div class="col-sm-4"></div>
            </div>
        </div>
    </div>
</div>


<script nonce="${scriptNonce}">

    $('#showPassword').click(function() { showPassword(); });
    $('#hidePassword').click(function() { hidePassword(); });

    if (window.location.hash) {
        $('#hash').val(window.location.hash);
    }

    function showPassword() {
        $('#password').prop('type', 'text');
        $('#showPassword').addClass('hidden');
        $('#hidePassword').removeClass('hidden');
        $('#password').focus();
    }

    function hidePassword() {
        $('#password').prop('type', 'password');
        $('#hidePassword').addClass('hidden');
        $('#showPassword').removeClass('hidden');
        $('#password').focus();
    }
</script>

structurizr-onpremises/src/main/webapp/WEB-INF/views/user-profile.jsp
<div class="section">
    <div class="container">
        <h1>User profile</h1>

        <p>
            Username: ${user.username}
        </p>

        <p>
            Roles:
        </p>

        <ul>
        <c:forEach var="role" items="${user.roles}">
            <li>${role}</li>
        </c:forEach>
        </ul>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/workspace-is-client-side-encrypted.jsp
<div class="section">
    <div class="container">
        <h1>Feature not available</h1>
        <p>
            The DSL editor is not available when your workspace is client-side encrypted.
        </p>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/workspace-is-readonly.jsp
<div class="section">
    <div class="container">
        <h1>Feature not available</h1>
        <p>
            You don't have write access to this workspace, so the editor feature is unavailable.
        </p>
    </div>
</div>

structurizr-onpremises/src/main/webapp/WEB-INF/views/workspace-locked.jsp
<div class="section">
    <div class="container">
        <h1>Workspace locked</h1>
        <p>
            This workspace was locked by <code>${workspace.lockedUser}</code> at <fmt:formatDate value="${workspace.lockedDate}" pattern="EEE dd MMM yyyy HH:mm z" timeZone="${user.timeZone}" />.
        </p>

        <p class="small">
            <a href="/workspace/${workspace.id}${urlSuffix}">Workspace summary</a>
            |
            <a href="/workspace/${workspace.id}/diagrams${urlSuffix}">Diagram viewer</a>
        </p>
    </div>
</div>